### PR TITLE
feat: Bump sdk v3.6.7 and redigo v.1.8 using gomod

### LINKED ISSUE #107: Update nri-redis to last skd v3 version to fix the multi-instance storage collision

### PR DESCRIPTION
**Pull request by gsanchezgavier**
- [x] - bump to go 1.16
- [x] - use go mod
- [x] - bump dependencies
- [x] - Add golanci-lint in ci/validate

fixes #107

### CODE REVIEW

**Comment by gsanchezgavier** [comment]
The project needs to be re-added to snyk after the PR is merge to use go.mod instead of govendor file.

**Comment by roobre** [comment]
`go-mod-upgrade` can bump a few outdated gomodules :)

```
> $ go-mod-upgrade
   • Discovering modules...
? Choose which modules to update  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [ ]  github.com/Sirupsen/logrus      0.11.5 -> 1.8.1
  [ ]  github.com/stretchr/testify     1.5.1  -> 1.7.0
  [ ]  github.com/xeipuuv/gojsonschema 1.1.0  -> 1.2.0
```

**Comment by gsanchezgavier** [comment]
Nice thanks @roobre i will run that

**Comment by gsanchezgavier** [comment]
still need to upgrade the third party notice . which will need some work on the papers-go repo

**Review by roobre — APPROVED** [review]
`All modules are up to date` 👌🏻

**Pull request merged**
